# Generated by Django 4.0 on 2021-12-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadesAcademicas',
            fields=[
                ('UnidadAcademicaId', models.AutoField(primary_key=True, serialize=False)),
                ('UnidadAcademicaName', models.CharField(max_length=255)),
                ('UnidadRegional', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesRegionales',
            fields=[
                ('UnidadRegionalId', models.AutoField(primary_key=True, serialize=False)),
                ('UnidadRegionalName', models.CharField(max_length=100)),
            ],
        ),
    ]
