# Generated by Django 4.0 on 2021-12-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioSocialApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='UnidadesAcademicas',
        ),
        migrations.DeleteModel(
            name='UnidadesRegionales',
        ),
    ]
