# Generated by Django 4.0 on 2022-01-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioSocialApp', '0004_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='modalidad',
            field=models.CharField(default='Escolarizada', max_length=250),
        ),
    ]
