# Generated by Django 4.0 on 2022-01-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioSocialApp', '0006_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('numdeinformes', models.CharField(max_length=50)),
                ('fase', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=250)),
            ],
        ),
    ]
