# Generated by Django 4.0 on 2022-01-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioSocialApp', '0010_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='departamento',
            new_name='dependencia',
        ),
    ]
