# Generated by Django 4.0 on 2022-01-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioSocialApp', '0015_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('apellido1', models.CharField(max_length=250)),
                ('apellido2', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=250)),
                ('unidadacademica', models.CharField(max_length=250)),
            ],
        ),
    ]
