# Generated by Django 4.0 on 2022-01-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioSocialApp', '0018_brigadista'),
    ]

    operations = [
        migrations.AddField(
            model_name='brigadista',
            name='numerodeinforme',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
